### ISSUE TITLE
Support for port 0 and host 0.0.0.0

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-websockets#12]
- Add tests for `0.0.0.0`
- Support returning the actual bound port if port `0` is being used

**Comment by dryajov** [comment]
This requires changing the underlying `pull-stream/pull-ws` to expose `server.address`. A PR to accomplish this is here - https://github.com/pull-stream/pull-ws/pull/21

**Comment by dryajov** [comment]
This PR should address resolving 0 addrs - #64

**Comment by diasdavid** [comment]
Woot, thank you @dryajov \o/

**Comment by diasdavid** [comment]
released in `v0.10.2`
