### ISSUE TITLE
Transport filters and `dnsaddr`

### ISSUE THREAD

**Issue by da-kami** [libp2p/js-libp2p-websockets#126]
We started using the [`dnsaddr` feature](https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md) and I was wondering how I can be combine that with the filter implementations 
as defined in the [websocket examples](https://github.com/libp2p/js-libp2p-websockets#constructor-properties) ([code](https://github.com/libp2p/js-libp2p-websockets/blob/master/src/filters.js))

I was unable to use the `dnsWsOrWss` filter in combination with our `dnsaddr` entries and was wondering why. Our TXT entries resolve to the IP address, potentially this is the problem. But I would have expected the filter to be valid for `dnsaddr` as well. 
Since we cannot use `dnsWsOrWss` we are using `all` for now, and in case we dial an unsupported transport address we just log a warning. Non-websocket transports may be dialed if the websocket connection runs into some error. This would not happen if we could use the filter.

I was wondering how this filter feature was meant to be used. I thought about adding an `ipWsOrWss` filter, or extend the `dns` part of the filter to accept `dnsaddr` (not sure if that can be achieved easily). But I am not sure that this goes towards the idea of how this was meant to be used so it would be great to get some input!

**Comment by vasco-santos** [comment]
Hello @da-kami 

Thanks for reaching out. `dnsaddr` feature basically allows us to have in a DNS TXT Entry several addresses for a given peer. Taking into account IPFS bootstrap addresses, we will get all the addresses that each peer has including: IPv4/IPv6 + TCP/Websockets/Quic

With the above in mind, the `dnsaddr` resolution happens up in the stack before reaching the transport level. The libp2p dial flow looks roughly like:

- (if dial with peerId) get the known peer addresses of the peer from the peerStore
- check if the known addresses are resolvable (`dnsaddr`) and resolve the resolvable ones
- go through each transport and use `transport.filter` to check which libp2p transport is valid for a given address
- dial using the obtained addresses

The motivation for using the filter function in `libp2p-websockets` is different. Browsers have strict security policies and only allow dials to addresses that both have DNS and WSS, unless localhost. Considering that nodes in the network advertise all types of addresses, it was quite common before we have these filters to have the browser console full of blocked dial attempts from the browser. So, by default libp2p in the browser will not dial unsafe addresses.

**Comment by lidel** [comment]
Assuming Vasco's response cleared things up. 
In the future, consider using discuss.ipfs.io for support questions, as more eyes is looking and you may get answers faster (+ we try for keep gh only for bugs and feature requests).
