### ISSUE TITLE
Cannot dial localhost peer over unsecured ws multiaddress

### ISSUE THREAD

**Issue by timfpark** [libp2p/js-libp2p-websockets#138]
I am trying to dial a local service running on localhost from the browser over a websocket with a multiaddress like `/ip4/127.0.0.1/tcp/8000/ws/p2p/QmQpHnb8k5gVze8PgqFZANMUf57apCWPjQihrXV53dkF2W` but this address is filtered by [src/filters.js](https://github.com/libp2p/js-libp2p-websockets/blob/90f13e935072a636609b8df1e3c3e814c7ff76ff/src/filters.js):

```
dnsWss: (multiaddrs) => multiaddrs.filter((ma) => {
    if (ma.protoCodes().includes(CODE_CIRCUIT)) {
      return false
    }

    const testMa = ma.decapsulateCode(CODE_P2P)

    return mafmt.WebSocketsSecure.matches(testMa) &&
      mafmt.DNS.matches(testMa.decapsulateCode(CODE_TCP).decapsulateCode(CODE_WSS))
  }),
```

I understand the intent here for dialing public addresses over secure websockets but it seems like within a host that it should be supported to dial without wss.  Thoughts?

**Comment by vasco-santos** [comment]
Hello @timfpark 

Yes, and that is valuable specially for testing. You can custom the filter with the All filter: https://github.com/libp2p/js-libp2p-websockets#libp2p-usage-example

**Comment by timfpark** [comment]
Ah - thanks @vasco-santos!

For future arrivals to this issue from a search engine, you can override this default check with a config block that looks like:

```
let libp2p = await Libp2p.create({
        peerId,
        modules: {
            transport: [Websockets],
            connEncryption: [NOISE],
            streamMuxer: [MPLEX],
        },
        config: {
            transport: {
                WebSockets: {
                    filter: filters.all,
                },
            },
        },
    });
  ```
