### ISSUE TITLE
Passing Strings instead of Buffers

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-websockets#28]
Got this while testing WebSockets with go-ipfs

```
Debug: internal, implementation, error
    Error: Uncaught error: data must be a buffer, was: "\u0013/multistream/1.0.0\n"
    at Object.add (/Users/david/code/js-ipfs/node_modules/pull-reader/state.js:18:15)
    at /Users/david/code/js-ipfs/node_modules/pull-reader/index.js:61:15
    at /Users/david/code/js-ipfs/node_modules/pull-reader/index.js:20:7
    at WebSocket.<anonymous> (/Users/david/code/js-ipfs/node_modules/pull-ws/source.js:23:14)
    at WebSocket.onMessage (/Users/david/code/js-ipfs/node_modules/ws/lib/WebSocket.js:442:14)
```

**Comment by dignifiedquire** [comment]
Could you please try and write a failing test case for this? That would make it easier to fix :)

**Comment by diasdavid** [comment]
@dignifiedquire absolutely, although a failing test case is hard because doing CI tests with go-ipfs is still not super smooth.

However, this seems that is a simple error coming from pull-ws, that is converting 'everything' to strings (kind of expected since WebSockets run in the browser and there is no native Buffer impl there') Will double check

**Comment by dignifiedquire** [comment]
I didn't mean a CI test with go, just a simple unit test that feeds in the same data, triggering this by itself

**Comment by diasdavid** [comment]
I believe this is now fixed (bug was coming from go), please confirm @dignifiedquire

**Comment by dignifiedquire** [comment]
@diasdavid I never saw this error, saw that's your call :)

**Comment by diasdavid** [comment]
I see. The way to test it is to make a dial from js-ipfs daemon to go-ipfs daemon while both using websockets (both have support for websockets on their master branches)

**Comment by dignifiedquire** [comment]
Oh, of course I talked to @whyrusleeping to fix this..I just forgot about it. Yes this can be closed :)
