### ISSUE TITLE
'.createServer' is undefined in browser

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-websockets#70]
The `.createServer` function should exist in the browser and return an error in the callback if called instead of simply being undefined

**Comment by dryajov** [comment]
I'm guessing that the listener should not be loaded in browsers at all, take a look at the websocket transport and how its loaded in `libp2p` - the dialer part is always loaded, but the listener doesn't get instantiated in the browser.

**Comment by mkg20001** [comment]
I was talking about replacing it with a function in the browser like `function createServer() { throw new Error('WebSockets servers can\'t be created in the browser'); }` instead of replacing the function with undefined and causing confusing error messages to appear in the browser.
