### ISSUE TITLE
WebSocket Error wss://ws-star.discovery.libp2p.io/socket.io

### ISSUE THREAD

**Issue by maxkerp** [libp2p/js-libp2p-websockets#74]
Hi there :)

I'm currently working on my bachelor's thesis in which I proof that creating WebComponents using [OrbitDB](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md) is possible. OrbitDB uses ipfs and its experimental pubsub feature, including the transport over WebSockets.

```
Addresses: {
  Swarm: [
    // Use IPFS dev signal server
    // '/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star',
    '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star',
    // Use local signal server
    // '/ip4/127.0.0.1/tcp/1337/ws/p2p-webrtc-star'
  ]
}
```

In the last couple of days I'm getting a lot of Errors when creating the ipfs node in the browser. `WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`.

My guess is that the traffic to this endpoint is getting pretty big. Are there any resources on how to setting up an own signaling server? My Professor is really interested in ipfs and its possibilities.
It might be possible to get a signaling server up and running at my college, maybe even a mirror of your whole setup to increase stability.

Any help is much appreciated :)

**Comment by sriharrsha** [comment]
I'm on 0.33.1 

![error](https://user-images.githubusercontent.com/5179687/50440217-c8f5c500-08ba-11e9-8abc-d5de7f41fe9d.png)

Never used wss1 or wss0 but somewhere the dependency libraries are hardcoded calling these servers.

Any Help?

**Comment by mizchi** [comment]
Same here with ipfs@0.33.1 (wss://sgp-1.bootstrap.libp2p.io/)

**Comment by mkg20001** [comment]
Btw, this should be moved to the ws-star repo as this isn't about libp2p-websockets

**Comment by Tryptophan** [comment]
Same issue here with ipfs@0.32.0.

**Comment by Juanperezc** [comment]
Guys ws-star.discovery.libp2p.io/socket.io  is down

**Comment by sriharrsha** [comment]
It is wss1 not ws-star. I figured out it is because of the cache somewhere in the older installation which is not overriden by the config.
When I tried on a fresh computer & browser this error didn't come up. So I reinstalle my browser an it vanished. There has to be a way when we update the packages to make it backward compatible.

**Comment by Tryptophan** [comment]
@Juanperezc is there a way to check the status of this discovery node? I've been retrying for the past day with no ability to connect.

**Comment by hushino** [comment]
same error with ipfs 0.33.1, node 10.14.2 and npm 6.5,

> websocket.js:110 WebSocket connection to 'wss://ws-star.discovery.libp2p.io/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

> transport.js:67 Uncaught Error: websocket error
>     at WS.Transport.onError (transport.js:67)
>     at WebSocket.ws.onerror (websocket.js:148)

**Comment by achingbrain** [comment]
This issue is about ws-star which is no longer supported since better methods of peer discovery are now available, consequently the `ws-star.discovery.libp2p.io` nodes have long been retired.  

For peer discovery the DHT can now be used instead.
